import "./global.css";
import Provider from "./provider";
import { Poppins } from "next/font/google";

export const metadata = {
  title: "Welcome to seller-ui",
  description: "Generated by create-nx-workspace",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "800", "700", "800"],
  variable: "--font-poppins",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen bg-slate-900 font-sans antialiased ${poppins.variable}`}
      >
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
